project:
  type: website
  execute-dir: project
  render: 
    - "*.qmd"
    - "!notebooks/population-assumptions.qmd"
    - "!notebooks/model-spec.qmd"
    - "!notebooks/decision-rules.qmd"
    - "!notebooks/sim-design4-results.qmd"
    - "!notebooks/sim-design5-data-smry.qmd"
    - "!notebooks/example-trials.qmd"
    - "!notebooks/trial-data.qmd"
    - "!backup/tmp.qmd"
    - "!backup/design-notes-06.qmd"
    - "!backup/design-notes-02-orig.qmd"
    - "!backup/trial-data.qmd"

website:
  title: "ROADMAP - design notes and simulations"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/maj-biostat/roadmap-sim
          - text: Report a Bug
            url:  https://github.com/maj-biostat/roadmap-sim/issues
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - section: "Assumptions and setup"
        contents:
        - notebooks/overview.qmd
        - notebooks/model-implementation.qmd
      - section: "Simulations"
        contents:
        - notebooks/sim-design1-results.qmd
        - notebooks/sim-design3-results.qmd
        - notebooks/sim-design5-results.qmd
        - notebooks/sim-design5-ex01.qmd
        - notebooks/sim-design5-ex02.qmd
        - notebooks/sim-design5-ex03.qmd
        - notebooks/sim-design6-results.qmd
        - notebooks/sim-design6-ex01.qmd
        - notebooks/sim-design6-ex02.qmd
        - notebooks/sim-design6-ex03.qmd
        - notebooks/sim-design7-results.qmd
      - section: "Design notes"
        contents:
        - notebooks/design-notes-01.qmd
        - notebooks/design-notes-02.qmd
        - notebooks/design-notes-03.qmd
        - notebooks/design-notes-04.qmd
        - notebooks/design-notes-05.qmd
        - notebooks/design-notes-06.qmd
        - notebooks/design-notes-07.qmd
        - notebooks/design-notes-08.qmd
        - notebooks/design-notes-09.qmd
        - notebooks/misc-notes.qmd
      - notebooks/about.qmd
          
format:
  html:
    # include-in-header: etc/mathjax.html
    theme:
      - sandstone
    toc: true
    code-fold: true
    code-line-numbers: true
    code-block-background: true
    toc-location: right
    toc-title: "Contents"
    toc-depth: 4
    toc-expand: true
    fig-width: 6
    fig-height: 4
    fig-dpi: 300
    fig-cap-location: margin
    tbl-cap-location: margin
    format-links: true
    html-math-method: mathjax
    classoption: fleqn
    highlight-style: arrow
    fontsize: 1em
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/github\.com'
    comments:
      hypothesis: true
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
    embed-resources: true



