# simulation configuration (all OR = log(1.2))
default:
  sc: "sc02"
  nsim: 10
  mc_cores: 5
  b_a_l_2: 0.1823216 # b_a_late_rev
  b_a_c_2: 0.1823216 # b_a_chronic_two
  b_b1_l_2: 0.1823216 # b_b1_late_one_w12p1
  b_b2_l_2: 0.1823216 # b_b2_late_two_w12p2
  b_b1_c_2: 0.1823216 # b_b1_chronic_one_w12p1
  b_b2_c_2: 0.1823216 # b_b2_chronic_two_w12p2
  b_c_2: 0.1823216 # b_c_rif
  d_sup: 0.950
  d_inf: 0.950
  d_fut: 0.050
  

