---
title: "Decision rules"
date: today
date-modified: last-modified
---

```{r, echo = FALSE}
source("./R/init.R")
log_info("Called model-spec notebook")
```

In the following, all treatment effect parameters relate back to the model specification provided earlier.

## Surgical domain

The surgical domain considers the effect of revision relative to dair in the late-stage infection silo.

Following the earlier [model specification](model-spec.qmd#sec-model-spec), let $\Delta_R = \beta_4 \mathbb{E}[\mathbb{I}(S_{R_P} == 1 \land R == 1)] + \beta_5 \mathbb{E}[\mathbb{I}(S_{R_P} == 2 \land R == 1)]$ correspond to the average conditional log-odds ratio associated with revision.
The probability that revision is superior to dair is defined as:

\begin{aligned}
P_{\text{surgical (sup)}} = Pr(\Delta_R > 0)
\end{aligned}

and enrolment is stopped for superiority if $P_{\text{surgical (sup)}} > 0.99$.

The probability of futility for revision being superior to dair is defined as:

\begin{aligned}
P_{\text{surgical (fut)}} = Pr(\Delta_R > \log(1.2))
\end{aligned}

and enrolment is stopped for futility if $P_{\text{surgical (fut)}} < 0.05$.

## Duration domain

The duration domain considers the effect of short relative to long duration therapy depending on the type of revision received.

If, in the surgical domain, revision is found to be inferior to DAIR, then randomisation in the surgical domain will cease and DAIR will be recommended for all late acute who meet the domain eligibility criteria.
But the duration domain will continue, because people in other silos will continue to have revision surgery (occasionally in Early and routinely in Chronic).

### DAIR 

No duration effects are applicable for DAIR.

### One-stage revision

Let $\beta_6$ correspond to the conditional log-odds ratio associated with 6 weeks (short) duration antibiotics relative to 12 weeks (long) when one-stage revision is received.
The probability that short is non-inferior to long is defined as:

\begin{aligned}
P_{\text{duration-1 (ni)}} = Pr(\beta_6 > \log(1/1.2))
\end{aligned}

and enrolment is stopped for non-inferiority if $P_{\text{duration-1 (ni)}} > 0.99$ or $P_{\text{duration-1 (ni)}} < 0.2$, the latter being taken to imply futility (with respect to being able to establish non-inferiority).

### Two-stage revision

Let $\beta_7$ correspond to the conditional log-odds ratio associated with 12 weeks (long) duration antibiotics relative to 7 days (short) when two-stage revision is received.
The probability that long duration is superior to short is defined as:

\begin{aligned}
P_{\text{duration-2 (sup)}} = Pr(\beta_7 > 0)
\end{aligned}

and enrolment is stopped for superiority if $P_{\text{duration-2 (sup)}} > 0.99$.

The probability of futility for long duration being superior to short is defined as:

\begin{aligned}
P_{\text{duration-2 (fut)}} = Pr(\beta_7 > \log(1.2))
\end{aligned}

and enrolment is stopped for futility if $P_{\text{duration-2 (fut)}} < 0.05$.


## Choice domain

The choice domain considers the effect of rifampacin relative to no-rifampacin.

Let $\beta_{9}$ correspond to the conditional log-odds ratio associated with rifampacin relative to no-rifampacin 
The probability that rifampacin is superior to no-rifampacin is defined as:

\begin{aligned}
P_{\text{choice (sup)}} = Pr(\beta_{9} > 0)
\end{aligned}

and enrolment is stopped for superiority if $P_{\text{choice (sup)}} > 0.99$.

The probability of futility for rifampacin being superior to no-rifampacin is defined as:

\begin{aligned}
P_{\text{choice (fut)}} = Pr(\beta_{9} > \log(1.2))
\end{aligned}

and enrolment is stopped for futility if $P_{\text{choice (fut)}} < 0.05$.