---
title: "Model specification"
date: today
date-modified: last-modified
---

```{r, echo = FALSE}
source("./R/init.R")
log_info("Called model-spec notebook")
```

## Primary outcome

The primary outcome is treatment success at 12 months post platform entry, defined as **all of**: 

1. Alive
2. Clinical cure (no clinical or microbiological evidence of infection)
3. No ongoing use of antibiotics for the index joint; and
4. The prosthesis present after the initial management strategy is complete (destination prosthesis) still in place

referred to as 'treatment success'.

## Early infection

Patients with early stage infection are not revealed^[Dependent on how the randomisation process is designed and implemented, they might not even be randomised.] to the surgical domain.
The surgical intervention will usually be dair for which 12 weeks of antibiotics are recommended.
There are, however, instances where early stage infection patients will receive a surgical intervention and these patients will therefore be able to enter the duration domain and receive randomised antibiotic duration.
These patients will also enter the choice domain.

## Late infection

Patients with late infection enter all domains, but with some restrictions.
They are randomised to dair vs revision in the surgical domain. 
Patients allocated to revision will receive a one or two-stage procedure.
Both the planned surgery (one-stage/two-stage) and the surgery actually performed should be captured -- the former should be recorded at the time of randomisation.
These patients will also enter the choice domain.

## Chronic infection

Patients with chronic stage infection are not randomised into the surgical domain, but they can enter into the duration domain based on the type of surgery they receive.
These patients will also enter the choice domain.

## Causal structure

We assume the following DAG, which is a simplified causal representation of how patients reach their treatment status across the domains:

```{mermaid}
%%| label: fig-modspec-1
%%| fig-cap: Assumed causal diagram representing the (simplified) processes on successful treatment
%%{
  init:{
    "flowchart":{"htmlLabels": "true"},
    "securityLevel": "loose",
    "theme": "base"
}}%%
flowchart LR
  ER(E<sub>R) --> RA(R<sub>A) 
  ER --> SR(S<sub>R)
  ED(E<sub>D) --> DA(D<sub>A) 
  SR --> RA 
  SD(S<sub>D) --> DA 
  R --> RA
  RA --> RP(R<sub>P) 
  SRP(S<sub>R<sub>P) --> RP
  RA --> Y
  RP --> ED
  D --> DA(D<sub>A)
  DA --> Y
  F --> FA(F<sub>A)
  EF(E<sub>F) --> FA
  SF(S<sub>F) --> FA 
  FA --> Y
  UER((U<sub>E<sub>R)) -.-> ER
  UED((U<sub>E<sub>D)) -.-> ED
  UEF((U<sub>E<sub>F)) -.-> EF
  UF((U<sub>F)) -.-> F
  URP((U<sub>R<sub>P)) -.-> SRP
  UD((U<sub>D)) -.-> D
  USR((U<sub>S<sub>R)) -.-> SR
  UR((U<sub>R)) -.-> R
  USD((U<sub>S<sub>D)) -.-> SD
  USF((U<sub>S<sub>F)) -.-> SF
  UY((U<sub>Y)) -.-> Y
```

where the following definitions apply:

-   $E_R$ reveal for surgical domain - 0: no, 1: yes
-   $E_D$ reveal for duration domain - 0: no, 1: yes
-   $E_F$ reveal for choice domain - 0: no, 1: yes
-   $R$ randomised surgery - 0: DAIR, 1: revision
-   $S_R$ revision type preference (pre-randomisation) - 0: DAIR, 1: one-stage, 2: two-stage
-   $R_A$ allocated surgery - 0: DAIR, 1: one-stage, 2: two-stage
-   $R_P$ performed surgery - 0: DAIR, 1: revision
-   $S_{R_P}$ revision type performed (post-randomisation) - 0: dair, 1: one-stage, 2: two-stage
-   $D$ randomised duration - 0: long, 1: short (for one-stage), 0: short, 1: long (for two-stage)
-   $D_A$ allocated duration - 0: long, 1: short, 2: other
-   $S_D$ selected duration - 0: long, 1: short, 2: other (sometimes duration will be selected rather than randomised)
-   $F$ randomised choice - 0: norif, 1: rif
-   $F_A$ allocated choice - 0: norif, 1: rif, 2: other
-   $S_F$ selected choice - 0: norif, 1: rif, 2: other
-   $Y$ treatment success - 0: no, 1: yes

## Research questions

The questions of interest are:

+ Surg Domain – Early Silo – Revision is superior to DAIR (reference group)
+ AB Duration – One-stage revision – 6 weeks (short) is non-inferior to 12 weeks (long) (reference group)
+ AB Duration – Two-stage revision – 12 weeks (long) is superior to 7 days (short) (reference group)
+ AB Choice – All silos combined – Rifampicin is superior to no-rifampicin (reference group)

## Model specification {#sec-model-spec}

For each silo $l$ and site of infection $j$ we therefore simulate and model the probability of treatment success as:

$$
\begin{aligned}
\mathbb{E}[Y|Q; \alpha,  \beta,\lambda] &=  \text{expit}( \alpha_0 + \\ 
  &\quad \lambda_1 \mathbb{I}(L = 1) + \lambda_2 \mathbb{I}(L = 2) + \\
  &\quad (\beta_1 + \beta_2 \mathbb{I}(S_{R_P} = 1) + \beta_3 \mathbb{I}(S_{R_P} = 2) ) (1-E_R) +\\ 
  &\quad (\beta_4 \mathbb{I}(S_{R_P} = 1) + \beta_5 \mathbb{I}(S_{R_P} = 2) )R E_R + \\
  &\quad \beta_6 (1-E_D) + \\
  &\quad (\beta_{7} \mathbb{I}(S_{R_P} = 1) + \beta_{8} \mathbb{I}(S_{R_P} = 2)])D E_D + \\
  &\quad \beta_{9} (1-E_F) + \beta_{10} F E_F )
\end{aligned}
$$ {#eq-mod-spec-1}

where the $Q$, $\alpha$, $\lambda$ and $\beta$ denote the terms and parameters included in the model and specifically

+ $\alpha_0$ denotes the baseline log-odds of treatment success 
+ $\lambda_1$ change associated with membership of the late silo
+ $\lambda_2$ change associated with membership of the chronic silo
+ $\beta_{1}$ change under non-randomised surgical treatment relative to randomised surgical treatment
+ $\beta_{2}$ relative change under non-randomised surgical treatment (receiving one-stage)
+ $\beta_{3}$ relative change under non-randomised surgical treatment (receiving two-stage)
+ $\beta_{4}$ change under randomised surgical treatment (revision) where one-stage procedure occurred
+ $\beta_{5}$ change under randomised surgical treatment (revision) where two-stage procedure occurred
+ $\beta_{6}$ change under non-randomised duration treatment
+ $\beta_{7}$ change for randomised duration treatment (short duration) when one-stage surgical procedure occurred
+ $\beta_{8}$ change for randomised duration treatment (long duration) when two-stage surgical procedure occurred
+ $\beta_{9}$ change under non-randomised choice treatment
+ $\beta_{10}$ change for randomised choice treatment (rif)

In order to easily evaluate the duration effects, we to make the reference arm 12-weeks (long) in the case of one-stage revision and 7-days (short) in the case of two-stage revision.

In the full model, there would be additional terms to capture time trends, site variation, prognostic covariates and joint (knee/hip) effects.

$\beta_1$, $\beta_2$ and $\beta_3$ are required because there will be some patients who are not randomised to revision and yet will still receive either a one-stage or two-stage surgical procedure. 
These patients may be eligible to enter into the duration domain and therefore the duration domain effects are informed by patients receiving randomised and non-randomised surgical treatment.
The $\beta_1$, $\beta_2$ and $\beta_3$ parameters provide adjustment for non-randomised surgical treatment and $\beta_4$ and $\beta_5$ provide adjustment for the patients that did.

Notice that $E_D = 0$ generally implies $S_{R_P} \notin \{1, 2\}$ such that $1-E_D$ is some linear function of the other terms in the model.
This can lead to estimation problems that might necessitate model re-parameterisation and it is for this reason that the simulation model drops the $(1 - E_D)$ term and re-index the $\beta$ parameters:


$$
\begin{aligned}
\mathbb{E}[Y|Q; \alpha,  \beta,\lambda] &=  \text{expit}( \alpha_0 + \\ 
  &\quad \lambda_1 \mathbb{I}(L = 1) + \lambda_2 \mathbb{I}(L = 2) + \\
  &\quad (\beta_1 + \beta_2 \mathbb{I}(S_{R_P} = 1) + \beta_3 \mathbb{I}(S_{R_P} = 2) ) (1-E_R) +\\ 
  &\quad (\beta_4 \mathbb{I}(S_{R_P} = 1) + \beta_5 \mathbb{I}(S_{R_P} = 2) )R E_R + \\
  &\quad (\beta_{6} \mathbb{I}(S_{R_P} = 1) + \beta_{7} \mathbb{I}(S_{R_P} = 2)])D E_D + \\
  &\quad \beta_{8} (1-E_F) + \beta_{9} F E_F )
\end{aligned}
$$ {#eq-mod-spec-2}


## Examples

The following characterise how patients enter into the likelihood under various scenarios under @eq-mod-spec-2.
The main consideration is whether randomised or non-randomised surgical treatment occurs and how this impacts the other terms in the model.

### Randomised surgical treatment


::: {.column width="100%"}

| ID | Covariate characteristics |  Log-odds treatment success |
|-|----|----|
| 1a | Late silo receiving rand DAIR, non-rand AB duration and rand rif |  $\alpha_0 + \lambda_1 + \beta_{9}$  |
| 2a | Late silo receiving rand rev (one-stage), rand 12 weeks AB (ref) and rand rif |  $\alpha_0 + \lambda_1 + \beta_4 + \beta_{9}$ |
| 3a | Late silo receiving rand rev (one-stage), rand 6 weeks AB and rand rif | $\alpha_0 + \lambda_1 + \beta_4 + \beta_6 + \beta_{9}$ |
| 4a | Late silo receiving rand rev (two-stage), rand 7 days AB (ref) and rand rif |  $\alpha_0 + \lambda_1 + \beta_5 + \beta_{9}$ |
| 5a | Late silo receiving rand rev (two-stage), rand 12 weeks AB and rand rif | $\alpha_0 + \lambda_1 + \beta_5 + \beta_7 + \beta_{9}$ |

: Likelihood contributions under various scenarios {.striped .hover}
:::



### Non-randomised surgical treatment


::: {.callout-note collapse=false}

Unsure whether non-randomised surgical treatment would occur for the late-silo patients but have included anyway.

If the non-reveal parameters for the surgical domain were not split by surgery type, then, in the following table:

+ ID 7b would have the same terms as ID 9b 
+ ID 12b would have the same terms as ID 14b

:::




::: {.column width="100%"}

| ID | Covariate characteristics |  Log-odds treatment success |
|-|----|----|
| 1b | Early silo receiving non-rand DAIR, non-rand AB duration and rand rif |  $\alpha_0 + \beta_1 + \beta_{9}$  |
| 2b | Early silo receiving non-rand rev (one-stage), rand 12 weeks AB (ref) and rand rif |  $\alpha_0 + \beta_1 + \beta_2 + \beta_{9}$  |
| 3b | Early silo receiving non-rand rev (one-stage), rand 6 weeks AB and rand rif |  $\alpha_0 + \beta_1 + \beta_2 + \beta_6 + \beta_{9}$  |
| 4b | Early silo receiving non-rand rev (two-stage), rand 7 days AB (ref) and rand rif |  $\alpha_0 + \beta_1 + \beta_3 + \beta_{9}$  |
| 5b | Early silo receiving non-rand rev (two-stage), rand 12 weeks AB and rand rif |  $\alpha_0 + \beta_1 + \beta_3 + \beta_7 + \beta_{9}$  |
|  | | |
| 6b | Late silo receiving non-rand DAIR, non-rand AB duration and rand rif |  $\alpha_0 + \lambda_1 + \beta_1 + \beta_{9}$  |
| 7b | Late silo receiving non-rand rev (one-stage), rand 12 weeks AB (ref) and rand rif |  $\alpha_0 + \lambda_1 + \beta_1 + \beta_2 + \beta_{9}$  |
| 8b | Late silo receiving non-rand rev (one-stage), rand 6 weeks AB and rand rif |  $\alpha_0 + \lambda_1 + \beta_1 + \beta_2 + \beta_6 + \beta_{9}$  |
| 9b | Late silo receiving non-rand rev (two-stage), rand 7 days AB (ref) and rand rif |  $\alpha_0 + \lambda_1 + \beta_1 + \beta_3 + \beta_{9}$  |
| 10b | Late silo receiving non-rand rev (two-stage), rand 12 weeks AB and rand rif |  $\alpha_0 + \lambda_1 + \beta_1 + \beta_3 + \beta_7 + \beta_{9}$  |
|  | | |
| 11b | Chronic silo receiving non-rand DAIR, non-rand AB duration and rand rif |  $\alpha_0 + \lambda_2 + \beta_1 + \beta_{9}$  |
| 12b | Chronic silo receiving non-rand rev (one-stage), rand 12 weeks AB (ref) and rand rif |  $\alpha_0 + \lambda_2 + \beta_1 + \beta_2 + \beta_{9}$  |
| 13b | Chronic silo receiving non-rand rev (one-stage), rand 6 weeks AB and rand rif |  $\alpha_0 + \lambda_2 + \beta_1 + \beta_2 + \beta_6 + \beta_{9}$  |
| 14b | Chronic silo receiving non-rand rev (two-stage), rand 7 days AB (ref) and rand rif |  $\alpha_0 + \lambda_2 + \beta_1 + \beta_3 + \beta_{9}$  |
| 15b | Chronic silo receiving non-rand rev (two-stage), rand 12 weeks AB and rand rif |  $\alpha_0 + \lambda_2 + \beta_1 + \beta_3 + \beta_7 + \beta_{9}$  |

: Likelihood contributions under various scenarios {.striped .hover}
:::






## Treatment effects

For the surgical domain, the effect of interest is an average conditional log-odds ratio and is applicable to the late silo.
This amounts to a weighted combination of $\beta_2$ and $\beta_3$ where the weights are the sample based expectations for the probability of receiving one-stage and two-stage surgery.

$$
\begin{aligned}
\Delta_R = \beta_4 \mathbb{E}[S_{R_P} == 1 \land R == 1] + \beta_5 \mathbb{E}[S_{R_P} == 2 \land R == 1]
\end{aligned}
$$

For the duration domain, the conditional log-odds ratios of interest are $\beta_6$ and $\beta_7$ which characterise the effect of 6 weeks (short) vs 12 weeks (long) under one-stage revision and 12 weeks (long) vs 7 days (short) in two-stage revision.
For the choice domain, the conditional log-odd ratios of interest is $\beta_{9}$, characterising the effect of rifampacin vs no-rifampacin.
For the duration and choice domains, the effects are applicable to all silos.


## Priors

As with the linear predictor, the priors are currently targeted towards the simulation work and may be modified in the final model.

### Intercepts

The silo and infection site intercepts are given independent normal priors

\begin{aligned}
\alpha_0 \sim \mathcal{N}(0, 1.5^2)
\end{aligned}

On the probability scale, these concentrate on 0.5 with 95% of the density between 0.04 and 0.96, approximately uniform across this interval.

### Other covariates

Independent standard normal priors are assumed for all other covariate terms effects.


### Treatment effects

All covariates relating to treatment effects have standard normal priors.